apiVersion: v1
kind: PersistentVolume
metadata:
  name: authservice-pv
  labels:
    type: local
spec:
  storageClassName: authservice-pvc-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/authservice-pvc-storage"

