apiVersion: v1
kind: PersistentVolume
metadata:
  name: katib-mysql-pv
  labels:
    type: local
spec:
  storageClassName: katib-mysql-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/katib-mysql-storage"
